namespace Herramientas;

public enum CodigosError
{
    ERR_ID_INEXISTENTE,
    ERR_CAMPO_REQUERIDO,
    ERR_CADENA_MUY_LARGA,
    ERR_DATOS_NO_VALIDOS,
    ERR_ERROR_NO_ESPECIFICADO,
    ERR_REGISTRO_DUPLICADO,
    ERR_REGISTRO_ELIMINADO,
    ERR_VALOR_FUERA_DE_RANGO,
}
